version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    container_name: elasticsearch
    networks: ['elk']
    ports:
    - 9200:9200
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks: ['elk']
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

networks:
  elk:

volumes:
  es_data: